version: "3"
services:
  problem-solving-cpp:
    build:
      context: ./c++
      dockerfile: Dockerfile.cpp
    image: problem-solving-cpp
    container_name: cpp
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./:/home"

  problem-solving-java:
    image: openjdk:11
    container_name: java
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./java:/home"